[package]
name = "imgui-sdl2"
version = "0.1.0"
authors = ["Michael Fairley <michael@michaelfairley.com>"]

[dependencies]
imgui = "0.0.18"
sdl2 = "0.31.0"

[dev-dependencies]
gl = "*"
imgui-opengl-renderer = "0.1.0"
